version: '3.7'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres:10.4-alpine
    env_file: ./.docker-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    init: true
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
